language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3

before_install:
  - curl -s http://getcomposer.org/installer | php
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
  - php composer.phar install --prefer-source --no-interaction
  - phpenv rehash

script:
  - MRGS_APP_ID=${MRGS_APP_ID} MRGS_CLIENT_SECRET=${MRGS_CLIENT_SECRET} MRGS_SERVER_SECRET=${MRGS_SERVER_SECRET} php vendor/bin/phpunit -c phpunit.xml
